### ISSUE TITLE
bt connection to close upon exit / SIGINT

### ISSUE THREAD

**Issue by noopkat** [noopkat/blend-micro-io#1]

**Comment by iamruinous** [comment]
This bug is causing us trouble on https://github.com/octoblu/meshblu-blendmicro. How can I help get a fix in place?

**Comment by noopkat** [comment]
Hi, can you please elaborate on how it fails? We can take it from there.
(and if you're already at a solution codewise, just a pull request is fine)

thanks!

**Comment by iamruinous** [comment]
```
Thu Feb 12 2015 10:46:40 GMT-0700 (MST) - TypeError: Cannot call method 'disconnect' of undefined
    at BlendMicro.module.exports.BlendMicro.close (/Users/octoblu/.config/gateblu/devices/006c4e40-b177-11e4-9dd2-0df5aacba31d/node_modules/blend-micro-io/node_modules/ble-firmata/node_modules/blendmicro/lib/blendmicro.js:111:30)
    at module.exports.BLEFirmata.close (/Users/octoblu/.config/gateblu/devices/006c4e40-b177-11e4-9dd2-0df5aacba31d/node_modules/blend-micro-io/node_modules/ble-firmata/lib/ble-firmata.js:152:23)
    at process.<anonymous> (/Users/octoblu/.config/gateblu/devices/006c4e40-b177-11e4-9dd2-0df5aacba31d/node_modules/blend-micro-io/blend-micro-io.js:85:11)
    at process.emit (events.js:92:17)
    at Signal.wrap.onsignal (node.js:761:46)
```

**Comment by noopkat** [comment]
aha thank you. By chance, are you using OSX Yosemite? That will help me debug as this OS still has some BT teething issues.
I'll work on getting this fixed for you asap.

**Comment by iamruinous** [comment]
Yes, using Yosemite. Happy to help test any patches.

Thank you!

**Comment by noopkat** [comment]
sorry just to deep dive to the final level of OS, are you on Yosemite 10.10.2? If you're not, could you please try updating to that if possible? I'm having trouble reproducing this error today, and have been able to in the past prior to 10.10.2.

**Comment by iamruinous** [comment]
I am currently on 10.10.2. It is happening when my app received SIGINT

**Comment by noopkat** [comment]
Thanks for the extra info. After testing on my end, would you mind updating to blend-micro-io@1.2.2 and retesting? Just published it [1.2.2](https://github.com/noopkat/blend-micro-io/releases/tag/v1.2.2)

**Comment by iamruinous** [comment]
That fixed it for me. Thanks for the super-fast fix. You rock!

**Comment by noopkat** [comment]
my pleasure!
